### ISSUE TITLE
Error in  perform.impostors

### ISSUE THREAD

**Issue by xudekuan** [computationalstylistics/stylo_howto#1]
When I used the funcion of perform.impostors, there appered a message:

Error in if (gsub("_.*", "", names(nearest)) == target.author) { : 
  argument is of length zero

my code is

perform.impostors (a, 
b,
iterations=10,
features=50, 
impostors=30, 

classes.candidate.set=c(rep("aaa_q", 93), "xxx_1" ),

classes.impostors.set=c(rep("bbb_q", 40)),

distance="delta", z.scores.both.sets=TRUE)

**Comment by computationalstylistics** [comment]
Hi there,
sorry for a late reply -- too many things on my plate. Thanks for pointing the issue. In the meantime, I have implemented a brand-new version of the imposters method: please refer to [this post](https://groups.google.com/forum/#!topic/computationalstylistics/ZnM2rUfKo8Q). I hope that the new implementation overcomes the issue!
